import {
  Award,
  Briefcase,
  FolderKanban,
  Globe,
  GraduationCap,
  Languages,
  Mail,
  PenTool,
  Trophy,
  UserRound,
  Wrench,
} from "lucide-react";
import type { SectionConfig } from "./types";

/**
 * Tüm bölümlerin tek kaynağı.
 * Yeni bölüm eklemek = buraya bir config eklemek (veri modeli supabase_schema.sql ile eşleşir).
 */
export const SECTION_CONFIGS: SectionConfig[] = [
  {
    id: "about",
    label: "Profil",
    icon: UserRound,
    table: "about_me",
    title: "Profil & Hakkımda",
    description: "İsim, unvan, slogan ve biyografi (tek satır form).",
    displayField: "name",
    singleRow: true,
fields: [
      { key: "name", label: "İsim", type: "text", required: true, placeholder: "Batuhan Dede" },
      { key: "role", label: "Unvan", type: "text", translatable: true, placeholder: "Frontend Developer" },
      { key: "hero_tagline", label: "Hero Sloganı", type: "text", translatable: true, placeholder: "Kısa tanıtım" },
      { key: "bio", label: "Biyografi", type: "textarea", translatable: true, textareaRows: 6, placeholder: "Kendinizi tanıtın..." },
      { key: "profile_photo_url", label: "Profil Fotoğrafı", type: "image_url", validate: "url", placeholder: "https://..." },
      { key: "show_profile_photo", label: "Fotoğrafı Göster", type: "checkbox", placeholder: "Sitede göster" },
    ],
  },
  {
    id: "experiences",
    label: "Deneyim",
    icon: Briefcase,
    table: "experiences",
    title: "Deneyim",
    description: "İş deneyimlerinizi yönetin.",
    displayField: "title",
    subtitleField: "company",
    imageField: "logo_url",
    fields: [
      { key: "title", label: "Pozisyon", type: "text", required: true, translatable: true, placeholder: "Software Engineer" },
      { key: "company", label: "Şirket", type: "text", required: true, translatable: true, placeholder: "Google" },
      { key: "location", label: "Konum", type: "text", translatable: true, placeholder: "İstanbul, Türkiye" },
      { key: "start_date", label: "Başlangıç", type: "month_year", placeholder: "Sep 2023" },
      { key: "end_date", label: "Bitiş", type: "month_year", isCurrentField: "is_current" },
      { key: "is_current", label: "Devam Ediyor", type: "checkbox", placeholder: "Şu an burada çalışıyor" },
      { key: "logo_url", label: "Logo URL", type: "image_url", validate: "url", placeholder: "https://..." },
      { key: "description", label: "Açıklama", type: "textarea", translatable: true, textareaRows: 4, placeholder: "Şirketteki görevinizi açıklayın..." },
      { key: "roles", label: "Pozisyonlar", type: "role_list" },
    ],
  },
  {
    id: "educations",
    label: "Eğitim",
    icon: GraduationCap,
    table: "educations",
    title: "Eğitim",
    description: "Eğitim geçmişinizi yönetin.",
    displayField: "university",
    subtitleField: "degree",
    imageField: "logo_url",
    fields: [
      { key: "university", label: "Üniversite", type: "text", required: true, translatable: true, placeholder: "Anadolu Üniversitesi" },
      { key: "degree", label: "Derece", type: "text", translatable: true, placeholder: "Lisans" },
      { key: "major", label: "Bölüm", type: "text", translatable: true, placeholder: "Yönetim Bilişim Sistemleri" },
      { key: "location", label: "Konum", type: "text", translatable: true, placeholder: "Eskişehir" },
      { key: "start_date", label: "Başlangıç", type: "month_year" },
      { key: "end_date", label: "Bitiş", type: "month_year", isCurrentField: "is_current" },
      { key: "is_current", label: "Devam Ediyor", type: "checkbox", placeholder: "Şu an okuyor" },
      { key: "gpa", label: "GPA / GANO", type: "text", placeholder: "3.50 / 4.00" },
      { key: "logo_url", label: "Logo URL", type: "image_url", validate: "url", placeholder: "https://..." },
    ],
  },
  {
    id: "skill_categories",
    label: "Yetenekler",
    icon: Wrench,
    table: "skill_categories",
    title: "Yetenek Kategorileri",
    description: "Yetenek gruplarını ve becerileri yönetin.",
    displayField: "title",
    fields: [
      { key: "title", label: "Kategori", type: "text", required: true, translatable: true, placeholder: "Frontend" },
      { key: "subtitle", label: "Alt Başlık", type: "text", translatable: true, placeholder: "Kısa açıklama" },
      { key: "skills", label: "Yetenekler", type: "json_array", translatable: true, placeholder: "React, Next.js, Tailwind" },
    ],
  },
  {
    id: "languages",
    label: "Diller",
    icon: Languages,
    table: "languages",
    title: "Diller",
    description: "Konuştuğunuz dilleri ve seviyelerini yönetin.",
    displayField: "name",
    subtitleField: "level",
    fields: [
      { key: "name", label: "Dil", type: "text", required: true, translatable: true, placeholder: "English" },
      {
        key: "level",
        label: "Seviye",
        type: "select",
        options: [
          { label: "Ana dil", value: "Native" },
          { label: "A1 - Başlangıç", value: "A1" },
          { label: "A2 - Temel", value: "A2" },
          { label: "B1 - Orta", value: "B1" },
          { label: "B2 - İleri Orta", value: "B2" },
          { label: "C1 - İleri", value: "C1" },
          { label: "C2 - Yetkin", value: "C2" },
        ],
      },
    ],
  },
  {
    id: "activities",
    label: "Liderlik & Etkinlikler",
    icon: Trophy,
    table: "activities",
    title: "Liderlik & Etkinlikler",
    description: "Kulüpler ve etkinlikleri yönetin.",
    displayField: "organization",
    subtitleField: "role",
    imageField: "logo_url",
    fields: [
      { key: "organization", label: "Kurum", type: "text", required: true, translatable: true, placeholder: "AI & Robotik Kulübü" },
      { key: "role", label: "Rol", type: "text", required: true, translatable: true, placeholder: "Başkan" },
      { key: "start_date", label: "Başlangıç", type: "month_year" },
      { key: "end_date", label: "Bitiş", type: "month_year", isCurrentField: "is_current" },
      { key: "is_current", label: "Devam Ediyor", type: "checkbox", placeholder: "Şu an aktif" },
      { key: "logo_url", label: "Logo URL", type: "image_url", validate: "url", placeholder: "https://..." },
      { key: "link_url", label: "Link", type: "text", validate: "url", placeholder: "https://..." },
      { key: "description", label: "Açıklama", type: "textarea", translatable: true, textareaRows: 4 },
      { key: "roles", label: "Pozisyonlar", type: "role_list" },
    ],
  },
  {
    id: "certifications",
    label: "Sertifikalar",
    icon: Award,
    table: "certifications",
    title: "Sertifikalar",
    description: "Sertifikaları ve bağlı yetenekleri yönetin.",
    displayField: "name",
    subtitleField: "issuer",
    imageField: "icon_url",
    junction: {
      table: "certification_skills",
      parentColumn: "certification_id",
      childColumn: "skill_category_id",
      sourceTable: "skill_categories",
      sourceLabelField: "title",
    },
    fields: [
      { key: "name", label: "Sertifika", type: "text", required: true, translatable: true, placeholder: "AWS Solutions Architect" },
      { key: "issuer", label: "Veren Kurum", type: "text", translatable: true, placeholder: "Amazon Web Services" },
      { key: "issue_date", label: "Tarih", type: "date", placeholder: "2024" },
      { key: "icon_url", label: "İkon URL", type: "image_url", validate: "url", placeholder: "https://..." },
      { key: "link_url", label: "Sertifika Linki", type: "text", validate: "url", placeholder: "https://..." },
    ],
  },
  {
    id: "projects",
    label: "Projeler",
    icon: FolderKanban,
    table: "projects",
    title: "Projeler / Çalışmalar",
    description: "Portfolyo projelerinizi ve galeri görsellerini yönetin.",
    displayField: "title",
    imageField: "image",
    filterField: "category",
    gallery: { table: "project_images", parentColumn: "project_id" },
    fields: [
      { key: "title", label: "Başlık", type: "text", required: true, translatable: true, placeholder: "Portföy Sitesi" },
      { key: "description", label: "Açıklama", type: "textarea", translatable: true, textareaRows: 4 },
      { key: "image", label: "Kapak Görseli", type: "image_url", validate: "url", placeholder: "https://..." },
      { key: "category", label: "Kategori", type: "text", placeholder: "web, mobil, ai..." },
      { key: "tags", label: "Etiketler", type: "json_array", placeholder: "React, Tailwind" },
      { key: "link", label: "Canlı Link", type: "text", validate: "url", placeholder: "https://..." },
      { key: "github", label: "GitHub", type: "text", validate: "url", placeholder: "https://github.com/..." },
      { key: "linked_experience_id", label: "Bağlı Deneyim", type: "select", sourceTable: "experiences", sourceValueField: "id", sourceLabelField: "company" },
      { key: "linked_education_id", label: "Bağlı Eğitim", type: "select", sourceTable: "educations", sourceValueField: "id", sourceLabelField: "university" },
      { key: "linked_language_id", label: "Bağlı Dil", type: "select", sourceTable: "languages", sourceValueField: "id", sourceLabelField: "name" },
      { key: "linked_activity_id", label: "Bağlı Etkinlik", type: "select", sourceTable: "activities", sourceValueField: "id", sourceLabelField: "organization" },
      { key: "linked_certification_id", label: "Bağlı Sertifika", type: "select", sourceTable: "certifications", sourceValueField: "id", sourceLabelField: "name" },
      { key: "linked_skill_category_ids", label: "Bağlı Yetenekler", type: "multi_select", sourceTable: "skill_categories", sourceValueField: "id", sourceLabelField: "title" },
    ],
  },
  {
    id: "blogs",
    label: "Blog",
    icon: PenTool,
    table: "blogs",
    title: "Blog Yazıları",
    description: "Yazıları, markdown içerikleri ve kapak görsellerini yönetin.",
    displayField: "title",
    imageField: "image_url",
    publishedField: "is_published",
    publishedLabel: "Yayında",
    gallery: { table: "blog_images", parentColumn: "blog_id" },
    fields: [
      { key: "title", label: "Başlık", type: "text", required: true, translatable: true, placeholder: "Yazı başlığı" },
      { key: "excerpt", label: "Özet", type: "textarea", translatable: true, textareaRows: 2 },
      { key: "content", label: "İçerik (Markdown)", type: "markdown", translatable: true, textareaRows: 12 },
      { key: "date", label: "Tarih", type: "date", placeholder: "22 Eyl 2026" },
      { key: "read_time", label: "Okuma Süresi", type: "text", placeholder: "5 dk" },
      { key: "image_url", label: "Kapak Görseli", type: "image_url", validate: "url", placeholder: "https://..." },
      { key: "is_published", label: "Yayında", type: "checkbox", placeholder: "Yayınla" },
      { key: "linked_project_id", label: "Bağlı Proje", type: "select", sourceTable: "projects", sourceValueField: "id", sourceLabelField: "title" },
      { key: "linked_experience_id", label: "Bağlı Deneyim", type: "select", sourceTable: "experiences", sourceValueField: "id", sourceLabelField: "company" },
      { key: "linked_education_id", label: "Bağlı Eğitim", type: "select", sourceTable: "educations", sourceValueField: "id", sourceLabelField: "university" },
      { key: "linked_language_id", label: "Bağlı Dil", type: "select", sourceTable: "languages", sourceValueField: "id", sourceLabelField: "name" },
      { key: "linked_activity_id", label: "Bağlı Etkinlik", type: "select", sourceTable: "activities", sourceValueField: "id", sourceLabelField: "organization" },
      { key: "linked_certification_id", label: "Bağlı Sertifika", type: "select", sourceTable: "certifications", sourceValueField: "id", sourceLabelField: "name" },
      { key: "linked_skill_category_ids", label: "Bağlı Yetenekler", type: "multi_select", sourceTable: "skill_categories", sourceValueField: "id", sourceLabelField: "title" },
    ],
  },
  {
    id: "social_links",
    label: "Sosyal Linkler",
    icon: Globe,
    table: "social_links",
    title: "Sosyal Linkler",
    description: "Sosyal medya bağlantılarını yönetin.",
    displayField: "platform",
    subtitleField: "url",
    fields: [
      {
        key: "platform",
        label: "Platform",
        type: "select",
        required: true,
        options: [
          { label: "LinkedIn", value: "LinkedIn" },
          { label: "GitHub", value: "GitHub" },
          { label: "Instagram", value: "Instagram" },
          { label: "X / Twitter", value: "X" },
          { label: "YouTube", value: "YouTube" },
          { label: "Dribbble", value: "Dribbble" },
          { label: "Resume (CV)", value: "Resume (CV)" },
          { label: "Diğer", value: "Other" },
        ],
      },
      { key: "url", label: "URL", type: "text", required: true, validate: "url", placeholder: "https://..." },
      {
        key: "icon",
        label: "İkon",
        type: "select",
        options: [
          { label: "GitHub", value: "Github" },
          { label: "LinkedIn", value: "Linkedin" },
          { label: "Instagram", value: "Instagram" },
          { label: "X (Twitter)", value: "Twitter" },
          { label: "YouTube", value: "Youtube" },
          { label: "E-posta", value: "Mail" },
          { label: "Globe", value: "Globe" },
          { label: "Diğer", value: "Other" },
        ],
      },
      { key: "account_type", label: "Hesap Türü", type: "text", placeholder: "personal, work..." },
    ],
  },
  {
    id: "contact_emails",
    label: "İletişim Mailleri",
    icon: Mail,
    table: "contact_emails",
    title: "İletişim Mailleri",
    description: "Görüntülenen e-posta adreslerini yönetin.",
    displayField: "label",
    subtitleField: "email",
    fields: [
      { key: "label", label: "Etiket", type: "text", required: true, translatable: true, placeholder: "Kişisel" },
      { key: "email", label: "E-posta", type: "text", required: true, validate: "email", placeholder: "ornek@site.com" },
    ],
  },
];

export type SectionId = (typeof SECTION_CONFIGS)[number]["id"];

/** Panel içi geçerli görünümler: dashboard, settings + her bölüm. */
export type AdminView = "dashboard" | "settings" | SectionId;

export const SECTION_MAP: Record<SectionId, SectionConfig> = Object.fromEntries(
  SECTION_CONFIGS.map((config) => [config.id, config]),
) as Record<SectionId, SectionConfig>;