import type { SectionConfig } from "./field-types";

export const SECTION_CONFIGS: SectionConfig[] = [
  {
    id: "experience",
    label: "Deneyim",
    icon: "Briefcase",
    table: "experiences",
    title: "Deneyim",
    description: "İş deneyimlerini yönet",
    displayField: "title",
    subtitleField: "company",
    imageField: "logo_url",
    fields: [
      { key: "title", label: "Pozisyon", type: "text", required: true, translatable: true, placeholder: "Software Engineer" },
      { key: "company", label: "Şirket", type: "text", required: true, placeholder: "Google" },
      { key: "location", label: "Konum", type: "text", translatable: true, placeholder: "İstanbul, Türkiye" },
      { key: "start_date", label: "Başlangıç", type: "month_year", placeholder: "Sep 2023" },
      { key: "end_date", label: "Bitiş", type: "month_year", isCurrentField: "is_current", placeholder: "Present" },
      { key: "is_current", label: "Devam ediyor", type: "checkbox", placeholder: "Şu an burada çalışıyor" },
      { key: "logo_url", label: "Logo URL", type: "image_url", placeholder: "https://..." },
      { key: "description", label: "Açıklama", type: "textarea", translatable: true, textareaRows: 4 },
      { key: "roles", label: "Pozisyonlar", type: "role_list", placeholder: "Bu şirketteki alt pozisyonlar" },
    ],
  },
  {
    id: "education",
    label: "Eğitim",
    icon: "GraduationCap",
    table: "educations",
    title: "Eğitim",
    description: "Eğitim geçmişini yönet",
    displayField: "university",
    subtitleField: "degree",
    imageField: "logo_url",
    fields: [
      { key: "university", label: "Üniversite", type: "text", required: true, translatable: true, placeholder: "MIT" },
      { key: "degree", label: "Derece", type: "text", translatable: true, placeholder: "Lisans" },
      { key: "major", label: "Bölüm", type: "text", translatable: true, placeholder: "Bilgisayar Bilimi" },
      { key: "location", label: "Konum", type: "text", translatable: true, placeholder: "İstanbul" },
      { key: "start_date", label: "Başlangıç", type: "month_year", placeholder: "2020" },
      { key: "end_date", label: "Bitiş", type: "month_year", isCurrentField: "is_current", placeholder: "2024" },
      { key: "is_current", label: "Devam ediyor", type: "checkbox", placeholder: "Şu an okuyor" },
      { key: "gpa", label: "GPA / GANO", type: "text", placeholder: "3.50 / 4.00" },
      { key: "logo_url", label: "Logo URL", type: "image_url", placeholder: "https://..." },
    ],
  },
  {
    id: "skills",
    label: "Yetenekler",
    icon: "Wrench",
    table: "skill_categories",
    title: "Yetenekler",
    description: "Yetenek kategorilerini yönet",
    displayField: "title",
    fields: [
      { key: "title", label: "Kategori", type: "text", required: true, translatable: true, placeholder: "Frontend" },
      { key: "skills", label: "Yetenekler (virgülle)", type: "json_array", translatable: true, placeholder: "React, Next.js, Tailwind" },
    ],
  },
  {
    id: "languages",
    label: "Diller",
    icon: "Languages",
    table: "languages",
    title: "Diller",
    description: "Bildiğin dilleri yönet",
    displayField: "name",
    subtitleField: "level",
    fields: [
      { key: "name", label: "Dil", type: "text", required: true, translatable: true, placeholder: "English" },
      {
        key: "level", label: "Seviye", type: "select",
        options: [
          { label: "Ana dil", value: "Native" },
          { label: "A1 - Başlangıç", value: "A1" },
          { label: "A2 - Temel", value: "A2" },
          { label: "B1 - Orta", value: "B1" },
          { label: "B2 - İleri Orta", value: "B2" },
          { label: "C1 - İleri", value: "C1" },
          { label: "C2 - Yetkin", value: "C2" },
        ],
      },
    ],
  },
  {
    id: "activities",
    label: "Liderlik & Etkinlikler",
    icon: "Trophy",
    table: "activities",
    title: "Liderlik & Etkinlikler",
    description: "Kulüpler ve etkinlikleri yönet",
    displayField: "organization",
    subtitleField: "role",
    imageField: "logo_url",
    fields: [
      { key: "organization", label: "Kurum", type: "text", required: true, translatable: true, placeholder: "AI & Robotik Kulübü" },
      { key: "role", label: "Rol", type: "text", required: true, translatable: true, placeholder: "Başkan" },
      { key: "start_date", label: "Başlangıç", type: "month_year", placeholder: "2023" },
      { key: "end_date", label: "Bitiş", type: "month_year", isCurrentField: "is_current", placeholder: "Present" },
      { key: "is_current", label: "Devam ediyor", type: "checkbox", placeholder: "Şu an aktif" },
      { key: "logo_url", label: "Logo URL", type: "image_url", placeholder: "https://..." },
      { key: "link_url", label: "Link", type: "text", placeholder: "https://..." },
      { key: "description", label: "Açıklama", type: "textarea", translatable: true, textareaRows: 4 },
      { key: "roles", label: "Pozisyonlar", type: "role_list", placeholder: "Bu kurumdaki alt pozisyonlar" },
    ],
  },
  {
    id: "certifications",
    label: "Sertifikalar",
    icon: "Award",
    table: "certifications",
    title: "Sertifikalar",
    description: "Sertifikaları yönet",
    displayField: "name",
    subtitleField: "issuer",
    imageField: "icon_url",
    fields: [
      { key: "name", label: "Sertifika", type: "text", required: true, translatable: true, placeholder: "AWS Solutions Architect" },
      { key: "issuer", label: "Veren Kurum", type: "text", required: true, placeholder: "Amazon Web Services" },
      { key: "issue_date", label: "Tarih", type: "date", placeholder: "2024" },
      { key: "icon_url", label: "İkon URL", type: "image_url", placeholder: "https://..." },
      { key: "link_url", label: "Sertifika Linki", type: "text", placeholder: "https://..." },
    ],
  },
  {
    id: "works",
    label: "Projeler",
    icon: "FolderKanban",
    table: "projects",
    title: "Çalışmalar / Projeler",
    description: "Portfolyo projelerini yönet",
    displayField: "title",
    subtitleField: "description",
    imageField: "image",
    fields: [
      { key: "title", label: "Başlık", type: "text", required: true, translatable: true, placeholder: "Portföy Sitesi" },
      { key: "description", label: "Açıklama", type: "textarea", translatable: true, textareaRows: 4 },
      { key: "image", label: "Kapak Görseli", type: "image_url", placeholder: "https://..." },
      { key: "category", label: "Kategori", type: "text", placeholder: "web, mobil..." },
      { key: "tags", label: "Etiketler (virgülle)", type: "json_array", placeholder: "React, Tailwind" },
      { key: "link", label: "Canlı Link", type: "text", placeholder: "https://..." },
      { key: "github", label: "GitHub", type: "text", placeholder: "https://github.com/..." },
      { key: "linked_experience_id", label: "Bağlı Deneyim", type: "select", sourceTable: "experiences", sourceValueField: "id", sourceLabelField: "company" },
      { key: "linked_education_id", label: "Bağlı Eğitim", type: "select", sourceTable: "educations", sourceValueField: "id", sourceLabelField: "university" },
      { key: "linked_language_id", label: "Bağlı Dil", type: "select", sourceTable: "languages", sourceValueField: "id", sourceLabelField: "name" },
      { key: "linked_activity_id", label: "Bağlı Etkinlik", type: "select", sourceTable: "activities", sourceValueField: "id", sourceLabelField: "organization" },
      { key: "linked_certification_id", label: "Bağlı Sertifika", type: "select", sourceTable: "certifications", sourceValueField: "id", sourceLabelField: "name" },
      { key: "linked_skill_category_ids", label: "Bağlı Yetenekler", type: "multi_select", sourceTable: "skill_categories", sourceValueField: "id", sourceLabelField: "title" },
    ],
  },
  {
    id: "blog",
    label: "Blog",
    icon: "PenTool",
    table: "blogs",
    title: "Blog Yazıları",
    description: "Yazıları yönet",
    displayField: "title",
    subtitleField: "excerpt",
    imageField: "image_url",
    publishedField: "is_published",
    publishedLabel: "Yayında",
    fields: [
      { key: "title", label: "Başlık", type: "text", required: true, translatable: true, placeholder: "Yazı başlığı" },
      { key: "excerpt", label: "Özet", type: "textarea", translatable: true, textareaRows: 2 },
      { key: "content", label: "İçerik (Markdown)", type: "textarea", translatable: true, textareaRows: 8 },
      { key: "date", label: "Tarih", type: "date", placeholder: "Sep 22, 2026" },
      { key: "read_time", label: "Okuma Süresi", type: "text", placeholder: "5 min read" },
      { key: "image_url", label: "Kapak Görseli", type: "image_url", placeholder: "https://..." },
      { key: "is_published", label: "Yayında", type: "checkbox", placeholder: "Yayınla" },
      { key: "linked_project_id", label: "Bağlı Proje", type: "select", sourceTable: "projects", sourceValueField: "id", sourceLabelField: "title" },
      { key: "linked_experience_id", label: "Bağlı Deneyim", type: "select", sourceTable: "experiences", sourceValueField: "id", sourceLabelField: "company" },
      { key: "linked_education_id", label: "Bağlı Eğitim", type: "select", sourceTable: "educations", sourceValueField: "id", sourceLabelField: "university" },
      { key: "linked_language_id", label: "Bağlı Dil", type: "select", sourceTable: "languages", sourceValueField: "id", sourceLabelField: "name" },
      { key: "linked_activity_id", label: "Bağlı Etkinlik", type: "select", sourceTable: "activities", sourceValueField: "id", sourceLabelField: "organization" },
      { key: "linked_certification_id", label: "Bağlı Sertifika", type: "select", sourceTable: "certifications", sourceValueField: "id", sourceLabelField: "name" },
      { key: "linked_skill_category_ids", label: "Bağlı Yetenekler", type: "multi_select", sourceTable: "skill_categories", sourceValueField: "id", sourceLabelField: "title" },
    ],
  },
  {
    id: "prototypes",
    label: "Prototipler",
    icon: "Smartphone",
    table: "prototypes",
    title: "Prototipler",
    description: "Prototip kayıtlarını yönet",
    displayField: "title",
    subtitleField: "description",
    imageField: "image_url",
    publishedField: "is_published",
    publishedLabel: "Yayında",
    fields: [
      { key: "title", label: "Başlık", type: "text", required: true, translatable: true, placeholder: "Prototip" },
      { key: "description", label: "Açıklama", type: "textarea", translatable: true, textareaRows: 3 },
      { key: "image_url", label: "Ekran Görseli", type: "image_url", placeholder: "https://..." },
      { key: "video_url", label: "Video URL", type: "text", placeholder: "https://..." },
      { key: "is_published", label: "Yayında", type: "checkbox", placeholder: "Sitede göster" },
    ],
  },
  {
    id: "uses",
    label: "Kullandıklarım",
    icon: "Cpu",
    table: "uses_categories",
    title: "Kullandıklarım",
    description: "Araç kategorilerini yönet",
    displayField: "title",
    fields: [
      { key: "title", label: "Kategori", type: "text", required: true, translatable: true, placeholder: "Editör" },
      { key: "items", label: "Araçlar (virgülle)", type: "json_array", translatable: true, placeholder: "VS Code, Cursor" },
    ],
  },
  {
    id: "gallery",
    label: "Galeri",
    icon: "ImageIcon",
    table: "gallery_items",
    title: "Galeri (Polaroid)",
    description: "Ana sayfa polaroid fotoğraflarını yönet",
    displayField: "caption",
    imageField: "image_url",
    publishedField: "is_published",
    publishedLabel: "Yayında",
    fields: [
      { key: "image_url", label: "Görsel URL", type: "image_url", required: true, placeholder: "https://..." },
      { key: "caption", label: "Altyazı", type: "text", translatable: true, placeholder: "Fotoğraf açıklaması" },
      { key: "is_published", label: "Yayında", type: "checkbox", placeholder: "Sitede göster" },
    ],
  },
  {
    id: "social",
    label: "Sosyal Linkler",
    icon: "Globe",
    table: "social_links",
    title: "Sosyal Linkler",
    description: "Sosyal medya bağlantılarını yönet",
    displayField: "platform",
    subtitleField: "url",
    fields: [
      { key: "platform", label: "Platform", type: "select", required: true,
        options: [
          { label: "LinkedIn", value: "LinkedIn" },
          { label: "GitHub", value: "GitHub" },
          { label: "Instagram", value: "Instagram" },
          { label: "X / Twitter", value: "X" },
          { label: "YouTube", value: "YouTube" },
          { label: "Dribbble", value: "Dribbble" },
          { label: "Resume (CV)", value: "Resume (CV)" },
          { label: "Diğer", value: "Other" },
        ] },
      { key: "url", label: "URL", type: "text", required: true, placeholder: "https://..." },
    ],
  },
  {
    id: "contact_emails",
    label: "İletişim Mailleri",
    icon: "Mail",
    table: "contact_emails",
    title: "İletişim Mailleri",
    description: "Görüntülenen e-posta adreslerini yönet",
    displayField: "label",
    subtitleField: "email",
    fields: [
      { key: "label", label: "Etiket", type: "text", translatable: true, placeholder: "Kişisel" },
      { key: "email", label: "E-posta", type: "text", required: true, placeholder: "ornek@site.com" },
    ],
  },
  {
    id: "easter_eggs",
    label: "Easter Egg'ler",
    icon: "Heart",
    table: "easter_eggs",
    title: "Easter Egg'ler",
    description: "Sürpriz görselleri yönet",
    displayField: "caption",
    imageField: "image_url",
    publishedField: "is_active",
    publishedLabel: "Aktif",
    fields: [
      { key: "image_url", label: "Görsel URL", type: "image_url", required: true, placeholder: "https://..." },
      { key: "caption", label: "Açıklama", type: "text", placeholder: "..." },
      { key: "is_active", label: "Aktif", type: "checkbox", placeholder: "Galeride göster" },
    ],
  },
];

export const ABOUT_CONFIG: SectionConfig = {
  id: "about",
  label: "Profil",
  icon: "UserCircle",
  table: "about_me",
  title: "Profil & Hakkımda",
  description: "Profil bilgilerini ve biyografiyi yönet",
  displayField: "name",
  singleRow: true,
  fields: [
    { key: "name", label: "İsim", type: "text", required: true, placeholder: "Batuhan Dede" },
    { key: "role", label: "Unvan", type: "text", translatable: true, placeholder: "Frontend Developer" },
    { key: "hero_tagline", label: "Hero Sloganı", type: "text", translatable: true, placeholder: "Kısa tanıtım" },
    { key: "bio", label: "Biyografi", type: "textarea", translatable: true, textareaRows: 6 },
    { key: "profile_photo_url", label: "Profil Fotoğrafı", type: "image_url", placeholder: "https://..." },
    { key: "started_coding_year", label: "Kodlama Başlangıç Yılı", type: "number", placeholder: "2019" },
    { key: "projects_count", label: "Proje Sayısı", type: "number", placeholder: "12" },
    { key: "years_experience", label: "Deneyim Yılı", type: "number", placeholder: "3" },
    { key: "quote_text", label: "Alıntı", type: "text", translatable: true, placeholder: "..." },
    { key: "quote_author", label: "Alıntı Sahibi", type: "text", placeholder: "..." },
    { key: "stat_1_value", label: "İstatistik 1", type: "text", placeholder: "2019" },
    { key: "stat_1_label", label: "İstatistik 1 Etiket", type: "text", translatable: true, placeholder: "Kodlamaya Başlangıç" },
    { key: "stat_2_value", label: "İstatistik 2", type: "text", placeholder: "12+" },
    { key: "stat_2_label", label: "İstatistik 2 Etiket", type: "text", translatable: true, placeholder: "Proje" },
    { key: "stat_3_value", label: "İstatistik 3", type: "text", placeholder: "3+" },
    { key: "stat_3_label", label: "İstatistik 3 Etiket", type: "text", translatable: true, placeholder: "Yıl Deneyim" },
    { key: "show_quote", label: "Alıntı göster", type: "checkbox", placeholder: "Sitede göster" },
    { key: "show_stats", label: "İstatistikleri göster", type: "checkbox", placeholder: "Sitede göster" },
    { key: "show_profile_photo", label: "Fotoğrafı göster", type: "checkbox", placeholder: "Sitede göster" },
  ],
};

export const SECTION_MAP: Record<string, SectionConfig> = Object.fromEntries(
  SECTION_CONFIGS.map((c) => [c.id, c]),
);